using OrderMauiApp.Services;
using OrderMauiApp.ViewModels;

namespace OrderMauiApp.Views;

public partial class InventoryView : ContentPage
{
    private const string KioskAdminEmail = "admin@example.com";
    private const string KioskAdminPassword = "password";
    private readonly InventoryViewModel _vm;

    public InventoryView(InventoryViewModel vm)
    {
        InitializeComponent();
        BindingContext = _vm = vm;
        LoginAdministrator();
    }

    private void LoginAdministrator()
    {
        var loginResult = DataService.LoginAdministratorAsync(KioskAdminEmail, KioskAdminPassword);
        Console.WriteLine("Administrator logged in.");
    }

    protected override async void OnAppearing()
    {
        base.OnAppearing();

        await DataService.RestoreAuthorizationAsync();

        var token = await DataService.GetBearerTokenAsync();
        if (string.IsNullOrWhiteSpace(token))
        {

            DataService.LogoutAdministrator();
            return;
        }

        // Only load once if empty
        if (_vm.InventoryList.Count == 0)
        {
            // Generated by [RelayCommand] on LoadInventoryAsync -> IAsyncRelayCommand LoadInventoryAsyncCommand
            await _vm.LoadInventoryCommand.ExecuteAsync(null);
        }
    }
}