name: Build and Push to GHCR

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        run: docker build -f ./karton-backend/backend.Dockerfile -t ghcr.io/kerpics-katrin-rebeka/leltarsupport-backend:latest ./karton-backend

      - name: Push backend image
        run: docker push ghcr.io/kerpics-katrin-rebeka/leltarsupport-backend:latest

      - name: Build frontend image
        run: docker build -f ./WEB/Web-Interface/frontend.Dockerfile -t ghcr.io/kerpics-katrin-rebeka/leltarsupport-frontend:latest ./WEB/Web-Interface

      - name: Push frontend image
        run: docker push ghcr.io/kerpics-katrin-rebeka/leltarsupport-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          printf '%s' "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to jcloud.jedlik
        run: |
          kubectl apply --server-side --force-conflicts --field-manager=github-actions -f ./k8s/database.yaml
          kubectl apply --server-side --force-conflicts --field-manager=github-actions -f ./k8s/backend.yaml
          kubectl apply --server-side --force-conflicts --field-manager=github-actions -f ./k8s/frontend.yaml

      - name: Restart deployments to pull latest images
        run: |
          kubectl rollout restart deployment/vizsgaremek-inventory-backend -n holbok-peter
          kubectl rollout restart deployment/vizsgaremek-inventory-frontend -n holbok-peter

      - name: Wait for rollouts
        run: |
          kubectl rollout status deployment/vizsgaremek-inventory-backend -n holbok-peter
          kubectl rollout status deployment/vizsgaremek-inventory-frontend -n holbok-peter